# Generated by Django 3.1.4 on 2021-01-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='entities',
            new_name='other_entities',
        ),
    ]
