# Generated by Django 3.1.4 on 2021-01-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210114_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['denomination']},
        ),
        migrations.AlterField(
            model_name='entity',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='Web'),
        ),
    ]
