# Generated by Django 3.1.4 on 2021-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210127_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog', verbose_name='logo'),
        ),
    ]
