# Generated by Django 3.1.4 on 2021-01-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_entity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog'),
        ),
    ]
