# Generated by Django 3.1.4 on 2021-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_entity_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/catalog'),
        ),
    ]
