# Generated by Django 3.1.4 on 2021-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210127_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email Asociado')),
                ('user_name', models.CharField(help_text='Nombre de usuario', max_length=20, verbose_name='Nombre de usuario')),
                ('social_media', models.CharField(help_text='Red social', max_length=20, verbose_name='Red social')),
                ('followers', models.IntegerField(verbose_name='Seguidores')),
                ('following', models.IntegerField(verbose_name='Seguidos')),
            ],
            options={
                'ordering': ['social_media'],
            },
        ),
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='catalog'),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=20, verbose_name='Nombre')),
                ('surname1', models.CharField(help_text='Primer apellido de la persona', max_length=20, verbose_name='Primer Apellido')),
                ('surname2', models.CharField(blank=True, help_text='Segundo apellido de la persona', max_length=20, null=True, verbose_name='Segundo Apellido')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('nationatility', models.CharField(help_text='Nacionalidad de la persona', max_length=20, verbose_name='Nacionalidad')),
                ('home_address', models.CharField(blank=True, help_text='Dirección de residencia', max_length=20, null=True, verbose_name='Lugar de residencia')),
                ('heritage', models.IntegerField(verbose_name='Patrimonio')),
                ('email_accounts', models.CharField(blank=True, help_text='Cuenta de email', max_length=50, null=True, verbose_name='Cuenta de email')),
                ('professional_activity', models.ManyToManyField(help_text='Empresas a cargo o para las que trabaja', max_length=50, to='catalog.Entity')),
                ('social_accounts', models.ManyToManyField(blank=True, help_text='Cuentas en redes sociales', max_length=50, null=True, to='catalog.SocialMediaAccount')),
            ],
            options={
                'ordering': ['surname1'],
            },
        ),
    ]
