# Generated by Django 3.1.4 on 2021-02-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
