# Generated by Django 3.1.7 on 2021-03-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='Email')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.RemoveField(
            model_name='individual',
            name='email_accounts',
        ),
        migrations.AddField(
            model_name='individual',
            name='email_accounts',
            field=models.ManyToManyField(blank=True, help_text='Cuentas de email', max_length=50, null=True, to='catalog.Email'),
        ),
    ]
