# Generated by Django 3.1.7 on 2021-03-03 21:50

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210303_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='Dirección')),
            ],
            options={
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='Tipo de vehículo')),
                ('number_plate', models.CharField(max_length=50, null=True, verbose_name='Matrícula')),
            ],
            options={
                'ordering': ['number_plate'],
            },
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'ordering': ['user_dni']},
        ),
        migrations.RemoveField(
            model_name='individual',
            name='heritage',
        ),
        migrations.AddField(
            model_name='individual',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='individual',
            name='user_dni',
            field=models.CharField(blank=True, help_text='DNI de la persona', max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='url',
            field=models.URLField(blank=True, help_text='URL de la cuent de usuario', null=True, verbose_name='URL de la cuenta de usuario'),
        ),
        migrations.AddField(
            model_name='socialmediaaccount',
            name='user_id',
            field=models.CharField(help_text='ID de la cuent de usuario', max_length=50, null=True, verbose_name='ID de la cuenta de usuario'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email_accounts',
            field=models.ManyToManyField(blank=True, help_text='Cuentas de email', max_length=50, to='catalog.Email'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='home_address',
            field=models.CharField(blank=True, help_text='Dirección de residencia', max_length=20, null=True, verbose_name=catalog.models.Address),
        ),
        migrations.AlterField(
            model_name='individual',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, help_text='Cuentas en redes sociales', max_length=50, to='catalog.SocialMediaAccount'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='email',
            field=models.CharField(help_text='Email asociado', max_length=50, null=True, verbose_name='Email Asociado'),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='social_media',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Whatsapp', 'Whatsapp'), ('Facebook', 'Facebook')], default=None, help_text='Red social', max_length=20, verbose_name='Red social'),
        ),
        migrations.AddField(
            model_name='individual',
            name='other_addresses',
            field=models.ManyToManyField(blank=True, help_text='Otras direcciones conocidas', max_length=20, to='catalog.Address'),
        ),
        migrations.AddField(
            model_name='individual',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Vehículos de su propiedad', max_length=50, to='catalog.Vehicle'),
        ),
    ]
