# Generated by Django 3.1.7 on 2021-03-03 22:42

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20210303_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='home_address',
            field=models.CharField(blank=True, help_text='Dirección de residencia', max_length=60, null=True, verbose_name=catalog.models.Address),
        ),
    ]
