# Generated by Django 3.1.7 on 2021-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20210304_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='charge',
            field=models.CharField(blank=True, help_text='Cargo que desempeña laboralmente', max_length=20, null=True, verbose_name='Cargo laboral'),
        ),
        migrations.AddField(
            model_name='individual',
            name='professional_status',
            field=models.CharField(default='Inactivo', help_text='Estatus laboral del individuo', max_length=20, verbose_name='Estatus Laboral'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_date_plate',
            field=models.DateField(blank=True, null=True, verbose_name='Primera matriculación'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
    ]
