# Generated by Django 3.1.7 on 2021-04-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210401_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='home_address_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Latitud de su última residencia conocida', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='home_address_longitud',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Longitud de su última residencia conocida', max_digits=12, null=True),
        ),
    ]
