# Generated by Django 3.1.7 on 2021-04-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210401_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='denomination',
        ),
        migrations.AddField(
            model_name='business',
            name='charge',
            field=models.CharField(blank=True, help_text='Cargo que desempeña en la entidad', max_length=20, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='business',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Desde'),
        ),
    ]
