# Generated by Django 3.1.7 on 2021-04-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210423_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='other_entities',
            field=models.ManyToManyField(blank=True, help_text='Otra entidad del administrador', null=True, to='catalog.Business'),
        ),
    ]
