# Generated by Django 3.1.7 on 2021-04-24 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210424_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(blank=True, help_text='Introduzca su nombre', max_length=200, null=True, verbose_name='Nombre')),
                ('note', models.CharField(help_text='Añade una anotación adicional sobre la entidad', max_length=200, verbose_name='Nota')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='notes',
            field=models.ManyToManyField(blank=True, help_text='Anotaciones adicionales', max_length=100, null=True, to='catalog.Note'),
        ),
    ]
