# Generated by Django 3.1.7 on 2021-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20210628_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
