# Generated by Django 3.1.7 on 2021-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_auto_20210628_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
