# Generated by Django 3.1.7 on 2021-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20210630_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
