# Generated by Django 3.1.7 on 2021-06-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_individual_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(help_text='Añade una anotación adicional sobre la entidad', max_length=200, verbose_name='Anotación'),
        ),
    ]
