# Generated by Django 3.1.7 on 2021-07-18 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0044_auto_20210708_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='borrower',
        ),
        migrations.AddField(
            model_name='entity',
            name='borrower',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
