# Generated by Django 3.1.7 on 2021-08-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20210728_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
