# Generated by Django 3.1.7 on 2021-08-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='number_of_agents',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='number_of_stockholders',
        ),
    ]
