# Generated by Django 3.1.7 on 2021-08-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20210807_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Cese de Actividad (inactiva)'), ('Disuelta', 'Disolución'), ('En Liquidación', 'Liquidación'), ('Extinguida', 'Extinción'), ('Suspensión de pagos', 'Suspensión de pagos'), ('Quiebra/Bancarrota', 'Quiebra/Bancarrota')], default='a', help_text='Estado de la entidad', max_length=50, verbose_name='Status'),
        ),
    ]
