# Generated by Django 3.1.7 on 2021-08-07 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20210807_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
    ]
