# Generated by Django 3.1.7 on 2021-08-15 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_auto_20210808_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='untill',
            field=models.DateField(blank=True, default=datetime.datetime.today, help_text='Fecha de cese', null=True, verbose_name='Hasta'),
        ),
    ]
