# Generated by Django 3.1.7 on 2021-08-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_auto_20210815_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='charge',
            field=models.CharField(help_text='Cargo en la entidad', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='name',
            field=models.CharField(help_text='Nombre completo', max_length=50, verbose_name='Nombre'),
        ),
    ]
